base_url = "https://rowsentinel.com"

[extra]
dontation_url = "http://uk.virginmoneygiving.com/fund/sentinel"
email = "northatlanticrower@marsandminerva.co.uk"
facebook_url = "https://www.facebook.com/rowsentinel"
twitter_url = "https://twitter.com/rowsentinel"
instagram_url = "http://instagram.com/rowsentinel"
youtube_url = "https://www.youtube.com/channel/UCMeP2FD61zwwsdtkMD0FmEw"
youtube_promo_url = "https://www.youtube.com/embed/eb4bH0K_5io"

grenade_url = "https://www.grenade.com/?utm_source=rowsentinal.com&utm_medium=referral&utm_campaign=row_sentinel"
spectragroup_url = "https://spectra-group.co.uk/"
hexegic_url = "https://www.hexegic.com"
valbruna_url = "http://www.valbruna.com.au"
drystone_url = "https://www.drystone.com/"
prometheus_url = "https://www.prometheusmedical.co.uk/"
velador_url = "https://veladorassociates.com"
silverback_url = "https://silverbacksecurityacademy.com"
dakin_url = ""
harwin_url = "https://www.harwin.com"
inspire_url = "http://www.inspirews.co.uk"
elliotbrown_url = "https://bit.ly/RowSentinelEB"
clearstorage_url = "https://clearstoragehereford.co.uk"

kinetic6_url = "https://www.kinetic6.co.uk"
serbus_url = "https://serbusgroup.com/secure-mobile-communication-tools"
levelpeaks_url = "https://www.levelpeaks.com"
halo_url = "https://haloleisure.org.uk"
carnegie_url = "https://www.leedsbeckett.ac.uk/carnegie-school-of-sport"
