base_url = "https://rowsentinel.com"

[extra]
dontation_url = "http://uk.virginmoneygiving.com/fund/sentinel"
email = "rowsentinelpress@outlook.com"
facebook_url = "https://www.facebook.com/rowsentinel"
twitter_url = "https://twitter.com/rowsentinel"
instagram_url = "http://instagram.com/rowsentinel"
youtube_url = "https://www.youtube.com/channel/UCMeP2FD61zwwsdtkMD0FmEw"
youtube_promo_url = "https://www.youtube.com/embed/eb4bH0K_5io"

tracking_url = "https://www.kinetic6tracks.com/s/33GT/ZT"

grenade_url = "https://www.grenade.com/?utm_source=rowsentinal.com&utm_medium=referral&utm_campaign=row_sentinel"
crye_url = "https://www.cryeprecision.com"
spectragroup_url = "https://spectra-group.co.uk/"
hexegic_url = "https://www.hexegic.com"
valbruna_url = "http://www.valbruna-stainless-steel.com"
drystone_url = "https://www.drystone.com/"
prometheus_url = "https://www.prometheusmedical.co.uk/"
velador_url = "https://veladorassociates.com"
silverback_url = "https://silverbacksecurityacademy.com"
dakin_url = ""
harwin_url = "https://www.harwin.com"
inspire_url = "http://www.inspirews.co.uk"
elliotbrown_url = "https://bit.ly/RowSentinelEB"
clearstorage_url = "https://clearstoragehereford.co.uk"
ct_url = "https://www.ctgroup.com"
rowell_url = "http://rowellyachtingservices.com/about-simon-rowell.html"

kinetic6_url = "https://www.kinetic6.co.uk"
serbus_url = "https://serbusgroup.com/secure-mobile-communication-tools"
levelpeaks_url = "https://www.levelpeaks.com"
halo_url = "https://haloleisure.org.uk"
carnegie_url = "https://www.leedsbeckett.ac.uk/carnegie-school-of-sport"
511_url = "https://www.511tactical.com/?SID=8098ae90d479ca8fb89d6132ec27918b"
