base_url = "https://rowsentinel.com"
compile_sass = true

[extra]
dontation_url = "http://uk.virginmoneygiving.com/fund/sentinel"
email = "northatlanticrower@marsandminerva.co.uk"
facebook_url = "https://www.facebook.com/rowsentinel"
twitter_url = "https://twitter.com/rowsentinel"
instagram_url = "http://instagram.com/rowsentinel"
youtube_url = "https://www.youtube.com/channel/UCMeP2FD61zwwsdtkMD0FmEw"
youtube_promo_url = "https://www.youtube.com/embed/eb4bH0K_5io"

spectragroup_url = "https://spectra-group.co.uk/"
drystonechambers_url = "https://www.drystone.com/"
prometheus_url = "https://www.prometheusmedical.co.uk/"
velador_url = "https://veladorassociates.com"

kinetic6_url = "https://www.kinetic6.co.uk"
serbus_url = "https://serbusgroup.com/secure-mobile-communication-tools"
levelpeaks_url = "https://www.levelpeaks.com"
