base_url = "https://rowsentinel.com"
compile_sass = true

[extra]
dontation_url = "https://uk.virginmoneygiving.com/charity-web/charity/finalCharityHomepage.action?charityId=1005329"
email = "northatlanticrower@marsandminerva.co.uk"
